---
- name: Reboot boxes
  command: shutdown -r now

- name: Wait for server to come back.
  local_action: wait_for
  args:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    delay: 60
    timeout: 300
    search_regex: OpenSSH
    state: started
  # Wait action runs on localhost, and does NOT require sudo.
  become: false
